### PR TITLE
Fixed steam logo not loading

### PR DESCRIPTION
**Pull request by HashEdits**
Hi, I fixed the import settings for the steam logo so that it's embeded in the final DLL alongside the line of code that loads said image.

### CODE REVIEW

**Comment by ykeara** [comment]
thanks not going to merge just this second. probably need to make a unique icon (i.e. not valve's), so as not to step on toes.

**Comment by HashEdits** [comment]
Here's Valve guidelines when it comes to utulizing the Steam logo and IP.

Hope this helps!

https://partner.steamgames.com/doc/marketing/branding
https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/french/Steam_Guidelines_060222.pdf

**Comment by HashEdits** [comment]
I did create a logo based on copying what was in the PDF:
steamlink


However I feel like the SteamLink in the string of the display name of the module is a bit redondent, what do you think about removing it if it's not used anywhere else? (the name in the registery is different)

| old | new |
| :-: | :-: |
 | image | image |


I'll add the apropriate commit depending on what you'd like :)

**Comment by ykeara** [comment]
Asking valve on guidance, my guess is they will want something a little different.

**Comment by ykeara** [comment]
@HashEdits for now I think we are good to go w/ the steam-link logo


Based on other module names I'm thinking "steamlink module" might actually be the better naming schema though rather than VRCFT module or Steamlink VRCFT module.

**Comment by HashEdits** [comment]
sounds good, I'm not super familair with pull requests but from what I've read it's not possible to add a new commit to that pull request, I'll make a new one with that new commit right now

**Comment by HashEdits** [comment]
woops, looks like it's all ready to go!

**Review by ykeara — APPROVED** [review]

**Pull request merged**
